apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guard
  labels:
    app: guard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guard
    spec:
      containers:
        - image: appscode/guard:canary
          name: guard
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: guard
  labels:
    app: guard
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: guard
