apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
  labels:
    app: kad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
        - image: appscode/kad:canary
          name: kad
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kad
  labels:
    app: kad
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: kad
